# Generated by Django 3.1.7 on 2021-05-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teams',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
