# Generated by Django 3.1.7 on 2021-05-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210527_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
