# Generated by Django 3.1.7 on 2021-08-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210821_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
