# Generated by Django 3.1.7 on 2021-08-22 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210822_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teams')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(through='api.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
