# Generated by Django 3.1.7 on 2021-05-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='teams',
            new_name='team',
        ),
    ]
