# Generated by Django 3.1.7 on 2021-05-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210518_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
    ]
