# Generated by Django 3.1.6 on 2021-08-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teammembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idRole', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamMembers',
        ),
        migrations.AddField(
            model_name='members',
            name='idRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles'),
        ),
        migrations.AddField(
            model_name='members',
            name='teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teams'),
        ),
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
