# Generated by Django 3.1.6 on 2021-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210820_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='idRole',
        ),
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
