# Generated by Django 3.1.6 on 2021-08-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210820_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='role',
            new_name='captain',
        ),
    ]
