# Generated by Django 3.1.7 on 2021-04-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Home',
        ),
    ]
